# Generated by Django 3.2.5 on 2024-02-27 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job',
        ),
    ]
