# Generated by Django 3.2.5 on 2024-02-27 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_ranking', '0001_initial'),
        ('resume_parser', '0002_remove_candidate_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='candidate_ranking.job'),
        ),
    ]
