# Generated by Django 3.2.5 on 2024-02-19 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_ranking', '0003_job_department'),
        ('resume_parser', '0003_auto_20240122_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job', to='candidate_ranking.job'),
        ),
    ]
