# Generated by Django 3.2.5 on 2024-02-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='break_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
