# Generated by Django 4.2.11 on 2024-04-22 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facial_recognition', '0002_alter_breakinandout_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakinandout',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='checkinandout',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
