# Generated by Django 4.2.11 on 2024-06-13 04:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('facial_recognition', '0003_alter_breakinandout_image_alter_checkinandout_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('working_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('working_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_bill_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=100)),
                ('comment', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_billing_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Billing',
                'verbose_name_plural': 'Attendance Billings',
            },
        ),
    ]
