# Generated by Django 3.2.5 on 2024-04-15 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240415_1430'),
        ('facial_recognition', '0003_checkinandout_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinandout',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='check_ins_and_check_outs', to='accounts.project'),
        ),
    ]
