# Generated by Django 3.2.5 on 2024-04-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240415_1430'),
        ('facial_recognition', '0004_alter_checkinandout_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakinandout',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='break_ins_and_break_outs', to='accounts.project'),
        ),
    ]
