# Generated by Django 3.2.5 on 2024-02-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_useraccount_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='emp_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
