# Generated by Django 3.2.5 on 2024-02-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccount_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='user_image',
            field=models.FileField(blank=True, null=True, upload_to='user_images/'),
        ),
    ]
