# Generated by Django 3.2.5 on 2024-04-17 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20240417_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='sbu_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accounts', to='accounts.subcategory'),
        ),
    ]
