# Generated by Django 3.2.5 on 2024-04-10 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20240410_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='contact_vip_id',
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.category'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='labour_license',
            field=models.FileField(blank=True, null=True, upload_to='agency_documents/'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agency',
            name='pan',
            field=models.FileField(blank=True, null=True, upload_to='agency_documents/'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='wcp',
            field=models.FileField(blank=True, null=True, upload_to='agency_documents/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.location'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='uhuh', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
