# Generated by Django 4.2.8 on 2024-04-23 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_agency_company_alter_agency_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='agency_id',
            field=models.CharField(max_length=10),
        ),
    ]
