# Generated by Django 3.2.5 on 2024-04-15 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20240415_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_accounts', to='accounts.location'),
        ),
    ]
