# Generated by Django 4.2.11 on 2024-06-13 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_agency_agency_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
