# Generated by Django 3.2.5 on 2024-04-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_useraccount_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='location',
        ),
    ]
