# Generated by Django 3.2.5 on 2024-02-21 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
