# Generated by Django 3.2.5 on 2024-02-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='departments',
            field=models.ManyToManyField(blank=True, null=True, related_name='jobs', to='candidate_ranking.Department'),
        ),
    ]
