# Generated by Django 3.2.5 on 2024-02-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobgroup',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
