# Generated by Django 3.2.5 on 2024-02-16 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_ranking', '0002_jobgroup_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='candidate_ranking.department'),
        ),
    ]
