# Generated by Django 3.2.5 on 2024-02-26 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_ranking', '0003_auto_20240226_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entity',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobgroup',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
