# Generated by Django 3.2.5 on 2024-03-14 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0005_auto_20240314_1045'),
        ('candidate_ranking', '0006_auto_20240226_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='entity',
        ),
        migrations.AlterField(
            model_name='department',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='app_settings.company'),
        ),
    ]
