# Generated by Django 3.2.5 on 2024-01-22 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='app_settings.customer'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='modules',
            field=models.ManyToManyField(related_name='customers', to='app_settings.Module'),
        ),
    ]
