# Generated by Django 3.2.5 on 2024-02-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_auto_20240226_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entities', to='app_settings.company'),
        ),
    ]
