# Generated by Django 3.2.5 on 2024-03-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_entity_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
