# Generated by Django 3.2.5 on 2024-03-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_ranking', '0007_auto_20240314_1045'),
        ('app_settings', '0005_auto_20240314_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
